# Generated by Django 4.0.5 on 2022-08-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='num_days',
            field=models.IntegerField(),
        ),
    ]
