# Generated by Django 4.0.5 on 2022-08-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_destination_delete_destinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCust',
            fields=[
                ('usercust_pk', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.TextField(max_length=50)),
                ('email_add', models.EmailField(max_length=254, unique=True)),
                ('mobile_num', models.IntegerField()),
                ('user_pass', models.CharField(max_length=10)),
            ],
        ),
    ]
